apiVersion: apps/v1
kind: Deployment
metadata:
  name: congrats-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: congrats-service
  template:
    metadata:
      labels:
        app: congrats-service
    spec:
      containers:
      - name: congrats-service
        image: badraaoumeur/congratulations3
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: congrats-service
  name: congrats-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http    
  selector:
    app: congrats-service
  type: NodePort
status:
  loadBalancer: {}
---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: congrats-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 8080
      name: http
      protocol: HTTP
    hosts:
    - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: congrats-service
spec:
  hosts:
  - "*"
  gateways:
  - congrats-gateway
  http:
  - match:
    - uri:
        prefix: "/" 
    route:
    - destination:
        host: congrats-service.default.svc.cluster.local
        port:
          number: 8080

