apiVersion: apps/v1
kind: Deployment
metadata:
  name: choice-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: choice-service
  template:
    metadata:
      labels:
        app: choice-service
    spec:
      containers:
      - name: choice-service
        image: badraaoumeur/choice2
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: choice-service
  name: choice-service
spec:
  ports:
  - port: 8081 
    protocol: TCP
    targetPort: 8081
    name: http    
  selector:
    app: choice-service
  type: NodePort
status:
  loadBalancer: {}
---

